import mongoose from "mongoose";

export const UserSchema = new mongoose.Schema({
  username: {
    type: String,
    required: [true, "Please provide unique Username"],
    unique: [true, "Username Exist"],
  },
  password: {
    type: String,
    required: [true, "Please provide a password"],
    unique: false,
  },
  email: {
    type: String,
    required: [true, "Please provide a unique email"],
    unique: true,
  },
  vaccination: { type: String },
  repeat: { type: String },
  supply: { type: String },
  regions: { type: String },
  specify: { type: String },
  bonus: { type: String },
  prevention: { type: String },
  often: { type: String },
  sarea: { type: String },
  program: { type: String },
  sregions: { type: String },
  hearingaid: { type: String},
  whichone: { type: String},
  harea: { type: String},
  hregions: { type: String},
  service: { type: String},
  preparation: { type: String},
  volume: { type: String},
  carea: { type: String},
  cregions: { type: String},
  cprogram: { type: String},
  foundation: { type: String},
  child: { type: String},
  farea: { type: String},
  fregions: { type: String},
  fprogram: { type: String},
  mobile: { type: Number },
  address: { type: String },
  profile: { type: String },
});

export default mongoose.model("User", UserSchema);

// {
//   "vaccination":"yes as a seperate service",
//   "often":"not often",
//   "supply":"yes",
//   "region":"Suna West32",
//   "bonus":"maybe",
//   "cancer":"no",
//   "hften":"not often",
//   "sarea":"no",
//   "regions":"region A",
//   "program":"maybe",
//   "hearingAid":"no",
//   "brand":"new",
//   "completearea":"yes",
//   "noregions":"region A",
//   "service":"maybe",
//   "childbirth":"yes as a seperate service",
//   "volume":"1000",
//   "birtharea":"yes",
//   "bregions":"region D",
//   "bprogram":"no",
//   "foundation":"no",
//   "explain":"i have this service for special conditions",
//   "csupply":"yes",
//   "carea":"region C",
//   "cprogram":"maybe"
// }