export const getFormData = (apiData) => {
    return {
        vaccination : apiData?.vaccination || '',
        repeat: apiData?.repeat || '',
        supply: apiData?.supply || '',
        regions: apiData?.regions || '',
        specify: apiData?.specify || '',
        bonus: apiData?.bonus || '',
        prevention: apiData?.prevention || '',
        often: apiData?.often || '',
        sarea: apiData?.sarea || '',
        sregions: apiData?.sregions || '',
        program: apiData?.program || '',
        hearingaid: apiData?.hearingaid || '',
        whichone: apiData?.whichone || '',
        harea: apiData?.harea || '',
        hregions: apiData?.hregions || '',
        service: apiData?.service || '',
        preparation: apiData?.preparation || '',
        carea: apiData?.carea || '',
        cregions: apiData?.cregions || '',
        cprogram: apiData?.cprogram || '',
        volume: apiData?.volume || '',
        foundation: apiData?.foundation || '',
        child: apiData?.child || '',
        farea: apiData?.farea || '',
        fregions: apiData?.fregions || '',
        fprogram: apiData?.fprogram || '',
        mobile: apiData?.mobile || '',
        address : apiData?.address || '',
    
        email: apiData?.email || "",
    };
  };